CREATE TABLE IF NOT EXISTS public.calendar_users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    email      varchar(256) UNIQUE                            NOT NULL,
    user_name  varchar(256) UNIQUE                            NOT NULL,
    first_name varchar(256),
    last_name  varchar(256),
    password   varchar(256)                                   NOT NULL,
    enabled    boolean
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    name varchar(20) UNIQUE
);

CREATE TABLE IF NOT EXISTS public.user_roles
(
    user_id bigint not null,
    role_id bigint not null,

    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),

    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES calendar_users (id) ON DELETE CASCADE,
    CONSTRAINT fk_roles FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.events
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    start_date  timestamp                                      NOT NULL,
    end_date    timestamp                                      NOT NULL,
    event_type  varchar                                        NOT NULL,
    name        varchar(255)                                   NOT NULL,
    description varchar(2000),
    owner_id    BIGINT                                         NOT NULL,

    CONSTRAINT fk_event_owner_id FOREIGN KEY (owner_id) REFERENCES calendar_users (id) ON DELETE CASCADE
)